.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "YEOMAN\-SERVER" "1" "July 2012" "" ""
.
.SH "NAME"
\fByeoman-server\fR \-\- Launch a preview server
.
.SH "SYNOPSIS"
.
.nf
yeoman server
.
.fi
.
.SH "DESCRIPTION"
This command \.\.\.
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
yeoman\-folders(1)
.
.IP "" 0

