.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "YEOMAN\-BOWER" "1" "July 2012" "" ""
.
.SH "NAME"
\fByeoman-bower\fR \-\- Specifics of yeoman\'s bower handling
.
.SH "SYNOPSIS"
.
.nf
yeoman install
yeoman uninstall
yeoman update
yeoman list
yeoman search
yeoman lookup
.
.fi
.
.SH "DESCRIPTION"
These commands \.\.\.
.
.IP "\(bu" 4
install: Install a package from the clientside package registry
.
.IP "\(bu" 4
uninstall: Uninstall the package
.
.IP "\(bu" 4
update: Update a package to the latest version
.
.IP "\(bu" 4
list: List the packages currently installed
.
.IP "\(bu" 4
search: Query the registry for matching package names
.
.IP "\(bu" 4
lookup: Look up info on a particular package
.
.IP "" 0
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
yeoman\-faq(1)
.
.IP "\(bu" 4
yeoman\-folders(1)
.
.IP "" 0

