.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "YEOMAN\-INIT" "1" "July 2012" "" ""
.
.SH "NAME"
\fByeoman-init\fR \-\- Initialize and scaffold a new project
.
.SH "SYNOPSIS"
.
.nf
yeoman init
.
.fi
.
.SH "DESCRIPTION"
This command \.\.\.
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
yeoman\-folders(1)
.
.IP "" 0

