.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "YEOMAN\-INSIGHT" "1" "July 2012" "" ""
.
.SH "NAME"
\fByeoman-insight\fR \-\- Specifics of yeoman insight
.
.SH "DESCRIPTION"
This document is all you need to know about what\'s done with insight, how it
works, what it does, and how you can configure its behaviour\.
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
yeoman\-folders(1)
.
.IP "" 0

