.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "YEOMAN\-BUILD" "1" "July 2012" "" ""
.
.SH "NAME"
\fByeoman-build\fR \-\- Build an optimized version of your app, ready to deploy
.
.SH "SYNOPSIS"
.
.nf
yeoman build
.
.fi
.
.SH "DESCRIPTION"
This command \.\.\.
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
yeoman\-folders(1)
.
.IP "" 0

