.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "YEOMAN\-FOLDERS" "1" "July 2012" "" ""
.
.SH "NAME"
\fByeoman-folders\fR \-\- Folder Structures Used by yeoman
.
.SH "DESCRIPTION"
When you generate a new application or trigger a new build, yeoman puts various
things on your computer\.
.
.P
This document will tell you what it puts where\.
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
yeoman\-faq(1)
.
.IP "\(bu" 4
yeoman\-gruntfile(1)
.
.IP "" 0

